### ISSUE TITLE
useSubscription closure not updated

### ISSUE THREAD

**Issue by Draeken** [crimx/observable-hooks#1]
Hello!

I have a similar use of useSubscription which access closure (a prop).

```typescript
const [debug, setDebug] = useState(false)
const subscription = useSubscription(events$, null, error => {
  if (debug) {
    console.log(error)
  }
})
```

But when the prop is updated, and useSubscription's  event handler is fired, it's always the old prop's value. I could add the prop in the observable used by useSubscription but it's cumbersome. Is there another way?

**Comment by crimx** [comment]
Hi! Are you using the latest version?

**Comment by crimx** [comment]
You can see the test here:

https://github.com/crimx/observable-hooks/blob/f8022b595f160a15539f7c6a0eca2557a596bb3a/test/use-subscription.spec.ts#L120-L123

If you are using v1 you have to create an extra Observable to track values and aso `useObservableCallback` to track the latest callback. In v2 I've simplify the API with just `useSubscription`.

**Comment by Draeken** [comment]
I was using v1 :open_mouth: 
It's much simpler now, thanks!
