### ISSUE TITLE
[Feature request]: useDebugValue

### ISSUE THREAD

**Issue by liaoyinglong** [crimx/observable-hooks#14]
some hooks should add `useDebugValue` to debug easier ?

**Comment by crimx** [comment]
In new [branch](https://github.com/crimx/observable-hooks/pull/11) I've added debug value for `useObservableState`. Any other hooks you think should also be added?

**Comment by liaoyinglong** [comment]
awesome!

and `useObservableSuspense` ?

**Comment by crimx** [comment]
`useDebugValue` is added in `observable-hooks@alpha`. Please give it a try. Any feedback is welcome!
