### ISSUE TITLE
Feature request: allow 'useObservableState' callback with no parameters

### ISSUE THREAD

**Issue by finnmerlett** [crimx/observable-hooks#16]
I'm just starting to use this library, and it looks amazing so far! I'm using the useObservableState function to watch responses from an observable. I need to be able to re-trigger the observable, so I've provided an init function. However, since I am just re-triggering the same observable I don't need to supply any parameters - but the useObservableState function update callback forces you to always supply 1 parameter, even if you specify the callback parameter type as undefined.

It's a small thing, but it would be lovely if when you specify the callback parameter type as undefined (and/or null maybe, or undefined in a type union?), that the callback function type would have the parameter as optional.

    const [num, refreshNum] = useObservableState<number, undefined>(
      () => getNumExternal$()
    );

    refreshNum(undefined)   // currently enforced format
    refreshNum()            // proposed format to be allowed

**Comment by crimx** [comment]
Is this what you want?

```
const num = useObservableState(
  useObservable(getNumExternal$)
)
```

**Comment by crimx** [comment]
Oh I see what you mean. You should use `void` instead of `undefined`.

**Comment by finnmerlett** [comment]
Fantastic, thank you! I didn't see it in the docs, though I might have missed it. Could be worth putting a note in there if it isn't already? Anyway, I have just tried using `void` and it's working perfectly. Cheers

**Comment by crimx** [comment]
This is just how `void` works. I'll add it to the docs as tips.
