### ISSUE TITLE
Execute twice when use useObserveableState & useSubscription together

### ISSUE THREAD

**Issue by FailLone** [crimx/observable-hooks#3]
## Steps to reproduce
1. useObservable

```js
const value$ = useObservable(input$ => input$ |> switchMap([v] => ajax(...)), [props.value])
```
2. useObservableState

```js
const value = useObservableState(value$)
```
3. useSubscription

```js
useSubscription(value$, v => props.onChange(v))
```
## What is expected?
just request once

## what is actually happening?
request twice

**Comment by FailLone** [comment]
Actually, this will happen when using `useObserveableState` & `useObservableCallback` together, too.

**Comment by crimx** [comment]
`useObservableState` is a sugar for `useSubscription`.

**Comment by crimx** [comment]
What did you want to achieve? If you need a state and also report to props you don't need `useObserveableState`. Just `useState` and do `setState` in `useSubscription`.

**Comment by FailLone** [comment]
So, that's not a bug.
Thanks for your carefully answers!
BTW, is it a good practice invoking props callback in `useObservable`? like:
```js
useObservable(input$ => input$ |> tap(([v]) => props.onChange(v)))
```

**Comment by crimx** [comment]
Yes. Callbacks in `useObservable` always reference to the latest context so it's safe to access states and props.

**Comment by crimx** [comment]
You should not do that in `useObservable`.

**Comment by FailLone** [comment]
It's a amazing project!
Thanks again!
