### ISSUE TITLE
`useObservableCallback`: allow callback with no parameters, or > 1 parameters

### ISSUE THREAD

**Issue by OliverJAsh** [crimx/observable-hooks#42]
In React we can use `useCallback` to define a callback with 0 parameters, like so:

```tsx
const callback = useCallback(() => 1, []);
// no error
callback();
```

If we try to do something similar using `useObservableCallback` we run into problems:

```tsx
const [callback, value$] = useObservableCallback((value$: Rx.Observable<never>) => value$);
// error
callback();
```

The difference between these two hooks is this: `useCallback` allows the callback to have any number of parameters, whereas `useObservableCallback` requires 1 parameter—no more and no less.

We could make `useObservableCallback` behave like `useCallback`:

```ts
declare function useObservableCallback<
    TInput extends Readonly<any[]>,
    TOutput = TInput,
    TParams extends Readonly<any[]> = TInput
>(
    init: (events$: Observable<TInput>) => Observable<TOutput>,
    selector?: (args: TParams) => TInput,
): [(...args: TParams) => void, Observable<TOutput>];

// 1 param
{
    const [callback, value$] = useObservableCallback(
        (value$: Observable<[number]>) => value$,
    );
    // no error
    callback(1);
}

// > 1 params
{
    const [callback, value$] = useObservableCallback(
        (value$: Observable<[number, string]>) => value$,
    );
    // no error
    callback(1, 'foo');
}

// 0 param
{
    const [callback, value$] = useObservableCallback(
        (value$: Observable<[]>) => value$,
    );
    // no error
    callback();
}
```

This gives us the most flexibility but it would be a breaking change because now the observable receives an array of parameters instead of just one parameter.

**Comment by OliverJAsh** [comment]
A workaround for defining callbacks with 0 parameters:

```ts
const [callback, value$] = useObservableCallback((value$: Rx.Observable<void>) => value$);
// no error
callback();
```

This doesn't help when you need > 1 parameters, but you can at least use an array:

```ts
const [callback, value$] = useObservableCallback((value$: Rx.Observable<[number, string]>) => value$);
// no error
callback([1, 'foo']);
```

**Comment by crimx** [comment]
https://observable-hooks.js.org/api/#useobservablecallback

Use it like this:

```ts
const [callback, value$] = useObservableCallback<number>(value$ => value$)
callback(1)
```

```ts
const [callback, value$] = useObservableCallback<
  boolean,
  boolean,
  [number, string]
>(value$ => value$)
callback(1, 'foo')
```

```ts
const [callback, value$] = useObservableCallback<void>(value$ => value$)
callback()
```

**Comment by OliverJAsh** [comment]
What about when you want to pass in multiple parameters for the observable to receive (rather than transforming them to a single parameter in the selector function)?

You can do this:

```ts
const [callback, value$] = useObservableCallback<[number, string]>(
    (value$) => value$,
);
callback([1, 'foo']);
```

but now the callback must receive an array, so it's not really "multiple parameters" like what we have with `useCallback`.

I also feel like the `void` technique for representing callbacks with 0 parameters is a bit of a hack. It works for sure, but it's not very obvious.

For these reasons I wonder whether we could improve on this with something like what I described above?

Side note: I realised the typings for `useObservableCallback` allow for mistakes such as the following:

```ts
const [callback, value$] = useObservableCallback<
    [number, string],
    [number, string],
    [number, string]
>((value$) => {
    // Type at runtime: Observable<number> - because we have no selector function
    // Type: Observable<[number, string]> - doesn't match runtime ❌
    return value$;
});
callback(1, 'foo');
```


Side note: I realised it's possible to

**Comment by crimx** [comment]
> What about when you want to pass in multiple parameters for the observable to receive (rather than transforming them to a single parameter in the selector function)?

like this?

```ts
const [callback, value$] = useObservableCallback<
  [number, string],
  [number, string],
  [number, string]
>(
  value$ => value$, // value is a observable of [number, string]
  identity
)
callback(1, 'foo')
```
