### ISSUE TITLE
useSubscription typescript wont allow undefined or null input$

### ISSUE THREAD

**Issue by finnmerlett** [crimx/observable-hooks#46]
In the docs it says that the `useSubscription` hook will take an input$ (first parameter) of `Observable<T> | null | undefined`, but the typescript type definition only allows `input$` to be of type `Observable<T>`. Is this intentional (and so a mistake in the docs), and mean the hook requires an observable `input$`, or is it a mistake in the typing definitions?

**Comment by crimx** [comment]
> In the docs it says that the useSubscription hook will take an input$ (first parameter) of Observable<T> | null | undefined

Can you provide a link to the docs so that I can better understand you question?

**Comment by crimx** [comment]
Oh I see what you meant. It's a mistake in the docs.

**Comment by crimx** [comment]
Fixed. Thanks for pointing out!

**Comment by finnmerlett** [comment]
No problem :) also respect for the super-speedy response, that's very impressive
