### ISSUE TITLE
为啥国内作者，文档全是英文呢？

### ISSUE THREAD

**Issue by Lind-pro** [crimx/observable-hooks#47]
靠翻译有点会理解偏

**Comment by crimx** [comment]
因为我目前没有时间维护两份文档了🙈考虑到国内开发者的英语能力普遍比国外开发者的中文能力好，所以先维护一份文档。

**Comment by Lind-pro** [comment]
> 因为我目前没有时间维护两份文档了🙈考虑到国内开发者的英语能力普遍比国外开发者的中文能力好，所以先维护一份文档。

好吧。那就凑合凑合先看英文的。

**Comment by crimx** [comment]
中文文档已写完 https://observable-hooks.js.org/zh-cn/
