### ISSUE TITLE
Provided sourcemaps reference the src folder which isn't distributed

### ISSUE THREAD

**Issue by cicloon** [crimx/observable-hooks#56]
Hi, I just noticed the sourcemaps published by the package aren't usable as they reference the src folder, which isn't present in the distributed package, for example: 
```
{"version":3,"file":"helpers.js","sourceRoot":"","sources":["../../src/helpers.ts"]...
``` 

This breaks packages that try to extract source-maps like https://github.com/webpack-contrib/source-map-loader or make they to don't work correctly.

**Comment by crimx** [comment]
Will this issue be fixed if we include the src folder in the distributed package?

**Comment by cicloon** [comment]
Yes!

Alejandro León

**Comment by crimx** [comment]
Published.
