### ISSUE TITLE
Feature proposal: A hook to create a Observable State

### ISSUE THREAD

**Issue by menosprezzi** [crimx/observable-hooks#70]
```ts
export default function useCreateObservableState<T>(initialState?: T): [Observable<T>, (v: T) => void] {
  const subject = useMemo(() => new BehaviorSubject<T>(initialState), []);
  const observable$ = useMemo(() => subject.asObservable(), [subject])

  const updateValue = (v: T) => {
    subject.next(v);
  };

  return [observable$, updateValue];
}
```

I don't know if this even makes sense. But maybe creating a BehaviorSubject in a _Reactish_ way is convenient. It'll be useful to provide an observable state store via ContextAPI (as a dependency injection tool).
I think that the usage of Context API + useState/useReducer doesn't scale and it brings performance issues (such as whole tree rerendering even if a component doesn't consume any value from the provided context)
Eg:
```ts
export interface UserState {
  name: string;
}

export const UserStoreContext = createContext<Observable<UserState>>(undefined as any);

export const UserStoreProvider = ({ children }) => {
  const [state$, setState] = useCreateObservableState<UserState>({ name: 'Joe Doe' });

  return <MyStoreContext.Provider value={state$}>{children}<MyStoreContext.Provider />
}

export const FancyUserName = () => {
  const user$ = useContext(UserStoreContext);
  const { name } = useObservableEagerState(user$);
  return <div style={{ color: 'red' }}>{name}</div>;
}
```

**Comment by menosprezzi** [comment]
Nevermind!

**Comment by crimx** [comment]
I believe what you want is alreay provided in observable-hooks. It's called [`useObservableCallback`](https://observable-hooks.js.org/api/#useobservablecallback)! Also check out the [concepts](https://observable-hooks.js.org/guide/core-concepts.html#function-callbacks).

> I think that the usage of Context API + useState/useReducer doesn't scale and it brings performance issues (such as whole tree rerendering even if a component doesn't consume any value from the provided context)

Exactly. But with `useObservableCallback`(which always returns the same observable) there will be no extra re-rendering triggered by context value.

Usage with React context is documented [here](https://observable-hooks.js.org/guide/context.html).
