### ISSUE TITLE
如何实现替换react官网的useEventCallback？

### ISSUE THREAD

**Issue by dragooncjw** [crimx/observable-hooks#95]
下图是react官网对`useEventCallback`的描述，文档里表示在任何情况下都不建议使用这个函数，
![image](https://user-images.githubusercontent.com/13393433/152958927-42aaff93-07f4-4259-ba51-8c5354257498.png)
我想使用observable-hooks库尝试实现替换react原生不被推荐的`useEventCallback`。

但是看了源码，发现`useSubscription`内的`observer`也是使用`useRef`实现的，那这样还是会存在渲染阶段的问题，我数据获取的时候只会获取到useRef初始化地方的变量，如果渲染阶段，在useRef后变量更新了，或者是在React并发模式下，还是会存在和`useEventCallback`一样的问题。

我如果将所有依赖都切换成`Observable`感觉处理起来会很麻烦，请问官方是否有合理的替代方案呢？

下面是我的代码：
```
export default function usePersistCallback<T>(
  observer?: (value: T) => void,
  init?: (events$: Observable<T>) => Observable<T>,
) {
  const [onEventTrigger, onEventTrigger$] = useObservableCallback(init);

  useSubscription(onEventTrigger$, observer);

  return onEventTrigger;
}
```
我将传给`useEventCallback`的函数替换成了`usePersistCallback`内的observer。

**Comment by crimx** [comment]
`useSubscription` 在触发回调前会先检查 staleness ，从而避免调用旧的回调。所以即便在渲染阶段也是调用正确的回调。

https://github.com/crimx/observable-hooks/blob/e29d60b9305ff9c1bc4d7ac225147ec2de6349be/packages/observable-hooks/src/internal/use-subscription-internal.ts#L38-L40

**Comment by dragooncjw** [comment]
其实我是想说我通过useSubscription的observer来实现的，这里看源码是通过useRef实现的。如果我使用input$来实现我想要实现的功能的话，会因为闭包，导致我在函数内部调用的永远是init时候的值。
https://github.com/crimx/observable-hooks/blob/e29d60b9305ff9c1bc4d7ac225147ec2de6349be/packages/observable-hooks/src/internal/use-subscription-internal.ts#L42

**Comment by crimx** [comment]
可以通过 codesandbox 构造一个例子说明你遇到的问题么？这里没看明白与 RxJS 有什么关系？

**Comment by crimx** [comment]
这是因为你的 `test` 放在了 `useObservableCallback` 的 `init` 回调中，[文档](https://observable-hooks.js.org/zh-cn/api/#useobservablecallback)已经说明 `init` 回调只会执行一遍。另外见[注意事项](https://observable-hooks.js.org/zh-cn/guide/gotchas.html#epic-%E9%97%AD%E5%8C%85)。

```ts
  const [onChangeTest, textChange$] = useObservableCallback((event$) =>
    event$.pipe(
      tap(() => {
        test("withMemo");
        setCounter((c) => c + 1);
      })
    )
  );
```

`tap` 是反 Rx 响应式模式所以一遍不推荐使用。

副作用放在 `useSubscription` 即可。

```ts
import { useObservableCallback, useSubscription, identity } from "observable-hooks";

  const [onChangeTest, textChange$] = useObservableCallback(identity);

  useSubscription(textChange$, () => {
    test("withMemo");
    setCounter((c) => c + 1);
  });
```

**Comment by dragooncjw** [comment]
是的，我一开始的问题里也写了我是使用了`useSubscription`里的observer实现解决的，但是问题在于我发现`useSubscription`源码里对observer内数据的同步还是通过使用`useRef`记录的，其实原理和使用`useEventCallback`是一样的，所以感觉使用您上一个回复中的方法并不能避免React官方文档中`useEventCallback`可能会出现的问题。

**Comment by crimx** [comment]
啊，是我记错了。之前举例的代码是用于检查 observable 更新的 staleness，不是检查回调的 staleness。

这个确实是与 `useEventCallback` 一样的，之前尝试过在 render 阶段赋值给 ref 但是因为有副作用会导致 React devtools 出错。

这个在 Observable 中可以接受是因为业务上限制了这个可能性。`useSubscription` 用于副作用的时候对于这个时机要求不敏感，用于 state 的时候因为 setState 都是一样的所以也不会出现问题。

**Comment by dragooncjw** [comment]
以后observable-hooks会推出相关的解决方案吗？我正在寻求`useEventCallback`的替代方案，但是没有找到好的解决方法

**Comment by crimx** [comment]
React 选择走上了函数组件+并行模式这条路决定了它不能在渲染阶段写带副作用的代码，所以 `useEventCallback` 这种模式只能通过业务设计上来规避，要么保证回调不会在渲染阶段触发，要么回调中不处理强依赖上下文的业务。而两种情况都需要的业务也非常少，通常都是反 React 模式的使用方式。

React 团队其实也知道这么结合代码不好写，所以拖了这么久 18 也没全上并行模式。

**Comment by dragooncjw** [comment]
感谢大佬指点
